### PR TITLE
I finished this project my_vivino

### PR DESCRIPTION
**Pull request by pulatov-x**

### CODE REVIEW

**Review by abdullaabdukulov — CHANGES_REQUESTED** [review]
I've reviewed your "My Vivino" project.

**Comment by abdullaabdukulov** [comment]
Rejected: "My Vivino" Project

Hi Xolid Pulatov,

I regret to inform you that your "My Vivino" project has been rejected due to unresolved issues, including bugs in your `classes` and `machine_learning` functions. Additionally, a separate `requirements.txt` file for external library packages is required.

Feel free to seek clarification or assistance.

Best,
Your Mentor Abdulla Abdukulov

**Comment by pulatov-x** [comment]
sorry, could you help a little bit
please tell me exactly what needs to be done with requirment.txt ?
What's it?

**Comment by pulatov-x** [comment]
> Я рассмотрел ваш проект «Мое Вивино».

sorry, could you help a little bit
please tell me exactly what needs to be done with requirment.txt ?
What's it?

**Pull request closed without merging**
